preprocessing:
  url_ai_act: https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=OJ:L_202401689
  file_path_extracted: data/json/ai_act_extracted.json
  file_path_chunks: data/json/ai_act_chunks.json
  file_path_chunks_split: data/json/ai_act_chunks_split.json
  chunk_overlap: 30
  split_threshold: 250
  chunk_size: 150

test_set:
  single_turn_path: data/test_set/golden_test_set.json
  multi_turn_path: data/test_set/multi_turn.json

vector_store:
  collection_name: ai_act_legal
  path: data/chroma_db
  embedding_model_map:
    bge-m3: BAAI/bge-m3
    snowflake-m: Snowflake/snowflake-arctic-embed-m
    minilm: sentence-transformers/all-MiniLM-L6-v2

rag_pipeline:
  embedding_model_name: snowflake-m
  llm_model: data/llm/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf
  ranker_model: ms-marco-MiniLM-L-12-v2
  history_length: 6
  retrieval_top_k: 5
  generation_max_new_tokens: 512
  max_token_context: 8192
  generation_temperature: 0.1
  generation_top_p: 0.9
  rerank_candidate_k: 20

streamlit:
  chat_history_file: results/streamlit/chat_history.json


#to download model: huggingface-cli download Bartowski/Meta-Llama-3.1-8B-Instruct-GGUF Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf --local-dir data/llm --local-dir-use-symlinks False



